name: Build snap package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: snapcore/action-build@v1
      id: snapcraft

    - name: Install snap
      run: sudo snap install --dangerous ${{ steps.snapcraft.outputs.snap }}

    - name: Run snap
      run: yubioath-desktop --version

    - uses: actions/upload-artifact@v2
      with:
        name: yubioath-desktop-snap
        path: ${{ steps.snapcraft.outputs.snap }}
